FROM confluentinc/cp-kafka-connect-base:7.3.0

COPY target/kafka-smt-aspectj-0.0.1-SNAPSHOT.jar /usr/share/java/kafka-smt-aspectj-0.0.1-SNAPSHOT.jar
COPY agent/aspectjweaver-1.8.9.jar /usr/share/java/aspectjweaver-1.8.9.jar
