FROM confluentinc/cp-kafka-connect-base:7.7.1

COPY agent/aspectjweaver-1.9.19.jar /usr/share/java/aspectjweaver-1.9.19.jar

COPY target/kafka-smt-aspectj-1.2.1.jar /etc/kafka-connect/jars/kafka-smt-aspectj-1.2.1.jar