FROM confluentinc/cp-kafka-connect-base:7.3.0

COPY agent/aspectjweaver-1.9.19.jar /usr/share/java/aspectjweaver-1.9.19.jar

COPY target/kafka-smt-aspectj-0.0.1-SNAPSHOT.jar /etc/kafka-connect/jars/kafka-smt-aspectj-0.0.1-SNAPSHOT.jar