---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-zookeeper:7.6.1
    init: confluentinc/confluent-init-container:2.8.2
  dataVolumeCapacity: 1Gi
  logVolumeCapacity: 1Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-kafka:7.6.1
    init: confluentinc/confluent-init-container:2.8.2
  dataVolumeCapacity: 1Gi
  metricReporter:
    enabled: false
---