apiVersion: batch/v1
kind: Job
metadata:
  name: order-service-job
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: simple
    spec:
      containers:
      - name: order-service
        env:
          - name: kafka.broker.list
            value: my-cluster-kafka-bootstrap:9092
        image: 172.30.1.1:5000/myproject/order-service
        command: ["java",  "-jar", "/deployments/order-service-0.0.1-SNAPSHOT.jar"]
      restartPolicy: OnFailure