## Minikube installation in Linux with KVM/QEMU
Follow instructions for ArchLinux (also tested with Fedora)

https://dev.to/xs/kubernetes-minikube-with-qemu-kvm-on-arch-312a

## Minikube installation in Mac/Windows

https://minikube.sigs.k8s.io/docs/start/

## Start Minikube with kvm2 driver

[source,bash]
----
minikube delete
minikube config set driver kvm2
touch /tmp/config && export KUBECONFIG=/tmp/config
minikube start --memory 16384 --cpus 4
----

## Create confluent k8s namespace

[source,bash]
----
kubectl create namespace confluent
kubectl config set-context --current --namespace confluent
----

## Add confluent repo to helm

[source,bash]
----
helm repo add confluentinc https://packages.confluent.io/helm
helm repo update
----

## Option 1: Install confluent-for-kubernetes operator from Confluent’s Helm repo

[source,bash]
----
helm upgrade --install confluent-operator confluentinc/confluent-for-kubernetes
----

## Option 2: Install confluent-for-kubernetes operator using the download bundle with license key

[source,bash]
----
wget https://confluent-for-kubernetes.s3-us-west-1.amazonaws.com/confluent-for-kubernetes-2.2.0.tar.gz
tar xvf confluent-for-kubernetes-2.2.0.tar.gz
helm upgrade --install confluent-operator ./confluent-for-kubernetes-2.2.0-20211101/helm/confluent-for-kubernetes --set licenseKey=<CFK license key>
----

## Option 1: Install Confluent components: 3 zk, 3 brokers, 1 connect, 1 ksqldb, 2 schema registry, 1 control center

[source,bash]
----
kubectl apply -f k8s/confluent-platform.yaml
----

## Option 2: Install Confluent components: 3 zk, 3 brokers, 1 control center

[source,bash]
----
kubectl apply -f k8s/confluent-platform-reducted.yaml
----

## Verify events and pods

[source,bash]
----
watch -n 5 "kubectl get events --sort-by='.lastTimestamp'"
watch -n 5 "kubectl get pods"
----

## Expose Control center on port 9021

[source,bash]
----
kubectl port-forward controlcenter-0 9021:9021
----

## Create a Topic named test-1

[source,bash]
----
kubectl apply -f k8s/topic.yml
----

## List Topics

[source,bash]
----
kubectl exec --stdin --tty kafka-0 -- /bin/bash
kafka-topics --bootstrap-server localhost:9092 --list
----

## Describe Topic test-1

[source,bash]
----
kubectl exec --stdin --tty kafka-0 -- /bin/bash
kafka-topics --bootstrap-server localhost:9092 --topic test-1 --describe
----

## Produce messages to topic test-1

[source,bash]
----
kubectl apply -f k8s/producer.yml
----

## Tear Down

Shut down Confluent Platform and the data:

[source,bash]
----
kubectl delete -f k8s/topic.yml
kubectl delete -f k8s/producer.yml
kubectl delete -f k8s/confluent-platform.yaml
helm delete confluent-operator
----

Delete namespace confluent:

[source,bash]
----
kubectl delete namespace confluent
----
