apiVersion: v1
kind: Service
metadata:
  name: kafka-streams-prometheus-service
  labels:
    app: kafka-streams-app
spec:
  type: NodePort
  selector:
    app: kafka-streams-prometheus-service
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      nodePort: 31234
