/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.hifly.kafka.demo.avro.references;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CarTelemetryData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3572532399579049041L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CarTelemetryData\",\"namespace\":\"org.hifly.kafka.demo.avro.references\",\"fields\":[{\"name\":\"speed\",\"type\":\"double\"},{\"name\":\"latitude\",\"type\":\"string\"},{\"name\":\"longitude\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CarTelemetryData> ENCODER =
      new BinaryMessageEncoder<CarTelemetryData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CarTelemetryData> DECODER =
      new BinaryMessageDecoder<CarTelemetryData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CarTelemetryData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CarTelemetryData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CarTelemetryData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CarTelemetryData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CarTelemetryData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CarTelemetryData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CarTelemetryData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CarTelemetryData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private double speed;
   private java.lang.CharSequence latitude;
   private java.lang.CharSequence longitude;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CarTelemetryData() {}

  /**
   * All-args constructor.
   * @param speed The new value for speed
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   */
  public CarTelemetryData(java.lang.Double speed, java.lang.CharSequence latitude, java.lang.CharSequence longitude) {
    this.speed = speed;
    this.latitude = latitude;
    this.longitude = longitude;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return speed;
    case 1: return latitude;
    case 2: return longitude;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: speed = (java.lang.Double)value$; break;
    case 1: latitude = (java.lang.CharSequence)value$; break;
    case 2: longitude = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'speed' field.
   * @return The value of the 'speed' field.
   */
  public double getSpeed() {
    return speed;
  }


  /**
   * Sets the value of the 'speed' field.
   * @param value the value to set.
   */
  public void setSpeed(double value) {
    this.speed = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public java.lang.CharSequence getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(java.lang.CharSequence value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public java.lang.CharSequence getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(java.lang.CharSequence value) {
    this.longitude = value;
  }

  /**
   * Creates a new CarTelemetryData RecordBuilder.
   * @return A new CarTelemetryData RecordBuilder
   */
  public static org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder newBuilder() {
    return new org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder();
  }

  /**
   * Creates a new CarTelemetryData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CarTelemetryData RecordBuilder
   */
  public static org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder newBuilder(org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder other) {
    if (other == null) {
      return new org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder();
    } else {
      return new org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder(other);
    }
  }

  /**
   * Creates a new CarTelemetryData RecordBuilder by copying an existing CarTelemetryData instance.
   * @param other The existing instance to copy.
   * @return A new CarTelemetryData RecordBuilder
   */
  public static org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder newBuilder(org.hifly.kafka.demo.avro.references.CarTelemetryData other) {
    if (other == null) {
      return new org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder();
    } else {
      return new org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder(other);
    }
  }

  /**
   * RecordBuilder for CarTelemetryData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CarTelemetryData>
    implements org.apache.avro.data.RecordBuilder<CarTelemetryData> {

    private double speed;
    private java.lang.CharSequence latitude;
    private java.lang.CharSequence longitude;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.speed)) {
        this.speed = data().deepCopy(fields()[0].schema(), other.speed);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.longitude)) {
        this.longitude = data().deepCopy(fields()[2].schema(), other.longitude);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CarTelemetryData instance
     * @param other The existing instance to copy.
     */
    private Builder(org.hifly.kafka.demo.avro.references.CarTelemetryData other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.speed)) {
        this.speed = data().deepCopy(fields()[0].schema(), other.speed);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.longitude)) {
        this.longitude = data().deepCopy(fields()[2].schema(), other.longitude);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'speed' field.
      * @return The value.
      */
    public double getSpeed() {
      return speed;
    }


    /**
      * Sets the value of the 'speed' field.
      * @param value The value of 'speed'.
      * @return This builder.
      */
    public org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder setSpeed(double value) {
      validate(fields()[0], value);
      this.speed = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'speed' field has been set.
      * @return True if the 'speed' field has been set, false otherwise.
      */
    public boolean hasSpeed() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'speed' field.
      * @return This builder.
      */
    public org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder clearSpeed() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder setLatitude(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.latitude = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder clearLatitude() {
      latitude = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder setLongitude(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.longitude = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public org.hifly.kafka.demo.avro.references.CarTelemetryData.Builder clearLongitude() {
      longitude = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CarTelemetryData build() {
      try {
        CarTelemetryData record = new CarTelemetryData();
        record.speed = fieldSetFlags()[0] ? this.speed : (java.lang.Double) defaultValue(fields()[0]);
        record.latitude = fieldSetFlags()[1] ? this.latitude : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.longitude = fieldSetFlags()[2] ? this.longitude : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CarTelemetryData>
    WRITER$ = (org.apache.avro.io.DatumWriter<CarTelemetryData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CarTelemetryData>
    READER$ = (org.apache.avro.io.DatumReader<CarTelemetryData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.speed);

    out.writeString(this.latitude);

    out.writeString(this.longitude);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.speed = in.readDouble();

      this.latitude = in.readString(this.latitude instanceof Utf8 ? (Utf8)this.latitude : null);

      this.longitude = in.readString(this.longitude instanceof Utf8 ? (Utf8)this.longitude : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.speed = in.readDouble();
          break;

        case 1:
          this.latitude = in.readString(this.latitude instanceof Utf8 ? (Utf8)this.latitude : null);
          break;

        case 2:
          this.longitude = in.readString(this.longitude instanceof Utf8 ? (Utf8)this.longitude : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










