# =========================
# HTTP
# =========================
quarkus.http.port=8080

# =========================
# Logging
# =========================
quarkus.log.console.enable=true
quarkus.log.console.level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# =========================
# Kafka Dev Services
# =========================
quarkus.kafka.devservices.enabled=false

# =========================
# Outgoing (Producer)
# =========================
mp.messaging.outgoing.demo-prod.bootstrap.servers=localhost:9092
mp.messaging.outgoing.demo-prod.topic=demo
mp.messaging.outgoing.demo-prod.connector=smallrye-kafka
mp.messaging.outgoing.demo-prod.acks=1

# =========================
# Incoming (Consumer)
# =========================
mp.messaging.incoming.demo.bootstrap.servers=localhost:9092
mp.messaging.incoming.demo.topic=demo
mp.messaging.incoming.demo.connector=smallrye-kafka