CREATE TABLE accounts (
    ID VARCHAR PRIMARY KEY,
    SSN VARCHAR
);

INSERT INTO accounts (ID, SSN) VALUES ('1', 'AAAA');
INSERT INTO accounts (ID, SSN) VALUES ('2', 'BBBB');
INSERT INTO accounts (ID, SSN) VALUES ('3', 'CCCC');
INSERT INTO accounts (ID, SSN) VALUES ('4', 'DDDD');
INSERT INTO accounts (ID, SSN) VALUES ('5', 'EEEE');