SET 'auto.offset.reset' = 'earliest';

CREATE STREAM TEMPERATURE_DATA (id BIGINT, body BIGINT) WITH (KAFKA_TOPIC='temperature.data',VALUE_FORMAT='JSON');
CREATE STREAM TEMPERATURE_DATA_STL AS SELECT ID,BODY FROM TEMPERATURE_DATA PARTITION BY id;

CREATE STREAM DEVICE (id BIGINT, fullname VARCHAR) WITH (KAFKA_TOPIC='device',VALUE_FORMAT='AVRO');
CREATE STREAM DEVICE_DATA AS SELECT ID,FULLNAME FROM DEVICE PARTITION BY id;
CREATE TABLE DEVICE_DATA_TBL(id BIGINT PRiMARY KEY, FULLNAME VARCHAR) WITH (KAFKA_TOPIC='DEVICE_DATA',VALUE_FORMAT='AVRO');

CREATE STREAM DEVICE_TEMPERATURE AS
      SELECT A.ID as DEVICE_ID,
             FULLNAME,
             BODY as TEMPERATURE
        FROM TEMPERATURE_DATA_STL A
             JOIN DEVICE_DATA_TBL B
             ON A.ID = B.ID;

CREATE STREAM DEVICE_TEMPERATURE_LJ AS
      SELECT A.ID as DEVICE_ID,
             FULLNAME,
             BODY as TEMPERATURE
        FROM TEMPERATURE_DATA_STL A
             LEFT JOIN DEVICE_DATA_TBL B
             ON A.ID = B.ID;


