SET 'auto.offset.reset' = 'earliest';

CREATE STREAM DEVICE (id BIGINT, fullname VARCHAR) WITH (KAFKA_TOPIC='device',VALUE_FORMAT='AVRO');
CREATE STREAM DEVICE_DATA AS SELECT ID,FULLNAME FROM DEVICE PARTITION BY id;
CREATE TABLE DEVICE_DATA_TBL(id BIGINT PRiMARY KEY, FULLNAME VARCHAR) WITH (KAFKA_TOPIC='DEVICE_DATA',VALUE_FORMAT='AVRO');

CREATE STREAM MAINTENANCE (id BIGINT, maintenance VARCHAR) WITH (KAFKA_TOPIC='maintenance',VALUE_FORMAT='AVRO');
CREATE STREAM MAINTENANCE_DATA AS SELECT ID,MAINTENANCE FROM MAINTENANCE PARTITION BY id;
CREATE TABLE MAINTENANCE_DATA_TBL(id BIGINT PRiMARY KEY, MAINTENANCE VARCHAR) WITH (KAFKA_TOPIC='MAINTENANCE_DATA',VALUE_FORMAT='AVRO');

CREATE TABLE DEVICE_MAINTENANCE AS
      SELECT A.ID as DEVICE_ID,
             FULLNAME,
             MAINTENANCE
        FROM MAINTENANCE_DATA_TBL A
             RIGHT JOIN DEVICE_DATA_TBL B
             ON A.ID = B.ID;


